<?php

$this->title = "Apagando Posts";
$this->headTitle($this->title);

?>

<p>Você tem certeza que deseja deletar '<?php echo $this->escape($this->album['title']); ?>' by '<?php echo $this->escape($this->album['artist']); ?>'</p>
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post">
	<div>
		<input type="hidden" name="id" value="<?php echo $this->album['id'];?>"/>
		<input type="submit" name="del" value="Sim"/>
		<input type="submit" name="del" value="N&atilde;o">
	</div>
</form>