<?php
    $this->title = "Meus Albuns";
    $this->headTitle($this->title);
?>
<p>
    <a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'add'));?>" class="btn btn-primary" >Adicionar Novo Album</a>
</p>
<table class="table table-striped">
    <tr>
        <th>Titulo</th>
        <th>Artista</th>
        <th>Ações</th>
    </tr>
    <?php foreach($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->title);?></td>
            <td><?php echo $this->escape($album->artist);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'edit', 'id'=>$album->id));?>">Editar</a>
                <a href="<?php echo $this->url(array('controller'=>'index',
                'action'=>'delete', 'id'=>$album->id));?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>